### ISSUE TITLE
Erro ao gerar uma versão Node.js da aplicação

### ISSUE THREAD

**Issue by silvioprog** [caio-ribeiro-pereira/meteor-bird#2]
Olá,

Como sou muito novo no ambiente Meteor, me deparei com um problema tanto em Linux quanto em Windows, daí não consigo gerar uma versão Node.js da aplicação.

O log completo do erro pode ser visto aqui: http://pastebin.com/MvZXuS0Q.

O estranho é o mesmo problema ocorrer em dois SOs distintos.

Alguém já se deparou com esse erro? Estou "pelejando" com isso desde sábado  e até agora nada rs.

Obrigado!

**Comment by silvioprog** [comment]
Opa, parece que é devido eu não ter o g++ nessa VM. Vou fazer a instalação dele e retorno caso isso resolva o pro ...

**Comment by silvioprog** [comment]
Depois de instalar o `g++` o erro no `npm install` não ocorreu mais, e o arquivo tar.gz foi gerado com sucesso, no entanto, quando tento rodar a aplicação gerada, recebo o seguinte erro:

```
$ MONGO_URL=mongodb://localhost:27017/meteorbird node main.js
/home/silvioprog/meteor-bird/meteor-bird/bundle/programs/server/node_modules/fibers/future.js:245
                        throw(ex);
                              ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at bindings (/home/silvioprog/meteor-bird/meteor-bird/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt/node_modules/bindings/bindings.js:74:15)
    at Object.<anonymous> (/home/silvioprog/meteor-bird/meteor-bird/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt/bcrypt.js:3:35)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
```

E os passos foram executados no exemplo original hospedado aqui no repositório do Caio. Segue os comandos que executei:

``` bash
$ git clone https://github.com/caio-ribeiro-pereira/meteor-bird.git
$ cd meteor-bird/
$ meteor build meteor-bird
$ cd meteor-bird/
$ tar -zxvf meteor-bird.tar.gz
$ cd bundle/programs/server/
$ npm install
$ cd ../../
$ MONGO_URL=mongodb://localhost:27017/meteorbird node main.js
```

No livro, este último comando (MONGO_URL=...) foi executado dentro da pasta `programs/server`, porém o arquivo `main.js` está dois níveis antes (por isso executei `cd ../../`).

Algum já conseguiu exportar um app Meteor para o Node.js e executá-lo em seguida?

Meu ambiente é um Linux Mint 64 bits, peguei o ISO da última versão lançada e instalei numa VM zerada.

**Comment by silvioprog** [comment]
Rapaziada, funcionou! =)

Comandos que executei:

``` bash
sudo apt-get remove gyp
sudo apt-get install node-gyp
rm -rf /home/ubuntu/meteorbird/programs/server/npm/npm-bcrypt
cd /home/ubuntu/meteorbird/programs/server
npm install bcrypt
cd ../../
```

Depois dei um:

``` bash
MONGO_URL=mongodb://localhost:27017/meteorbird ROOT_URL=http://localhost PORT=3000 node main.js
```

E Eureka! =)
